### ISSUE TITLE
翻译错误：Translate Error: NotFound

### ISSUE THREAD

**Issue by tankc07** [LoveHikari/comment-translator#2]
- Visual Studio: VS2022 17.3.5
- This extension: Version-1.0.3

![image](https://user-images.githubusercontent.com/40915940/194789576-3ccaf896-8a27-44a4-af9c-9c74a981d6b2.png)

挂不挂梯子都不行，不知道是什么原因。也不知道在哪里设置谷歌TKK。

**Comment by LoveHikari** [comment]
已修复，原因是近期google翻译中国服务已经停止，代码中使用的是cn域名，导致404，现已改为com
