### ISSUE TITLE
翻译长时间未响应

### ISSUE THREAD

**Issue by zhaifanhua** [LoveHikari/comment-translator#3]
### Installed product versions
- Visual Studio: Community 2022 (64 位) - Current 版本 17.5.2
- This extension: 1.0.4

### Description
翻译长时间未响应

### Steps to recreate
![image](https://user-images.githubusercontent.com/106963561/225531363-44216f5d-0045-45a4-bbae-bba64108653e.png)

**Comment by zhaifanhua** [comment]
我使用的是百度翻译

**Comment by LoveHikari** [comment]
目前，百度翻译无法使用，请优先所有其他翻译

**Comment by zhaifanhua** [comment]
bing，有道等都用不了

**Comment by LoveHikari** [comment]
已修复
