### ISSUE TITLE
希望增加引用翻译功能

### ISSUE THREAD

**Issue by CHN-STUDENT** [LoveHikari/comment-translator#4]
RT，可否大佬加一个形如vscode插件一样的函数引用翻译
不知道难度如何，感觉俺这种菜鸟只能提提需求...不会修改和PR

![image](https://github.com/LoveHikari/comment-translator/assets/21209416/2610d67c-950d-43d0-a5d1-6d5c1500abf3)

![image](https://github.com/LoveHikari/comment-translator/assets/21209416/86e6bd74-e391-487d-b1f6-74fb4bcb454e)

> https://github.com/intellism/vscode-comment-translate
> https://learn.microsoft.com/zh-cn/visualstudio/extensibility/walkthrough-displaying-quickinfo-tooltips?view=vs-2022&tabs=csharp

**Comment by LoveHikari** [comment]
vs智能提示的内容似乎是不能被插件修改的，需要修改提示文本的话，可以修改引用库中的xml文件

**Comment by LoveHikari** [comment]
已添加
